# Generated by Django 3.2.7 on 2021-09-30 03:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0002_auto_20210930_0321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='MessagesCount',
        ),
    ]
